language: cpp
sudo: required
matrix:
  include:
  - os: linux
  - os: linux
    env: KALABOX_TEST_GROUP=cmd
  - os: osx
before_install:
- cp ci/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
- $HOME/travis-ci.sh before-install
install:
- $HOME/travis-ci.sh install
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
- $HOME/travis-ci.sh before-deploy
after_deploy:
- $HOME/travis-ci.sh after-deploy
cache:
  directories:
  - node_modules
notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalabox.io
    - riley@kalabox.io
    - alec@kalabox.io
    on_success: always
deploy:
  - provider: releases
    api_key:
      secure: RzNqrN6xhmPdVzFn23bU67rLkKqfJmPJqSqrcSrvXEhVml92jl7OeGNZ/2tWaI6HxT89QymZ7cP65aRse7WxKDIwg6wrmmJ3T9n4EamW3EmVGNh1Kg6Coe9T2BavxVgoezDXmPM/LP23BivUAJNa+dxIWRtk7dNpnwveINLMPY1BxcMJPnxkohSH+Kh1MvGc9AaowdN/N6tMP1N+yOOQ1IvJyhRnyL9XeNJWKnXJVxqODIQuQaujX3bA1TKaFdEANudq1431wOWjlDLGQYqhFr9xZLthuxUe7hYzUvJZW0+m2TAnAkvwMlLcRpJrmCxbqEzpbTDDHhEv63uKuFz2bvOrVpayvngR0VB5CausWdTidFwuvKEac7AT5UUP916epREhWpl0ZLrZ1zdjrq7uz8gnn6XCicIO3tah2By5O61wCVcg2BSKIKt63vWn3kMjR2NYpdQ7viq+R/z6LkZMN72WRrKy0LkdGPISYtOAHzR6wfk33m3Xa/qta8xCMkofZmjC0fxP0kBhuUGziGMAVmSaY34lvFPUowdvsr3hNmJjFzS6jhR9+Lk7HXEjizYOdt8yx5r5qPFJuuIOo43ZZqns/202ZpjUJqf88cf0puNe9PRmmjDeAH3p3zFkIi1kTMl/o/8vZx6VPB7pqVWaeFnrcVnJAFOh8nr0zR/q9M4=
    file: prod_build/kbox-$TRAVIS_OS_NAME-x64-$TRAVIS_TAG
    skip_cleanup: true
    on:
      repo: kalabox/kalabox-cli
      tags: true
  - provider: npm
    email: mike@kalamuna.com
    api_key:
      secure: lQvsejToxCatY3EbpNp4U5msbTMAzSj7SkvxD/0pe3lCD9loQFR0lAjdMSplt1v2zGsPZiRtL2FhT+UE78QNK6AHkdW+sT1Ze7Hl4QbgheMfr9eGwmsRAeU3wOsUbACR1suV46INS1Pkc9LMa3WF56X+MCMDk7Aj/SzwUGmQimOhD31EBSvYk9uZUjLQCF5nXOth068z6MKO/bBJcbwmGA0kOpwz1AnjVdLX+Qft/GPKboTIv7GVKA+gEmLZrN3PVSoXWE+tgR8kiq0UEiXCocNT9YsMj/ewA5vQ5ZSqu9oGAsBDCYAhMSTbEft1zFgGdz1ouuUMAi9cVitXwMW1DXx7ndJrtoRzZW9zvXkBkNQYcjLsuSpjgzGIlJzjIkIWNLMc71PdMccTfmXxxJTvmY/eMRpkfBCB2SMg82V2xHBoSSW9/1cORiWYqEjGKW6l+/GAygYqGtE4moQKxTN6e0WDJGgJlfZm9e+2x0vhcCpTXZl6s7EDvCMsDnneD1EyymVwWUH4x37D7X+wnL6/vmuL15zm/IsgoWuzl5IiTpTQFu7ls6hwzt7zy4H/iOjsChZXMM/XvU2dnAUOvFUqHcXl3I6yhsNgqhXJvH5sVspfGJcCvTMW1Tgtnqw4DejCkXtCHEScGjWqACuXLNbDS8B2FJsOIE5f9y10j5RjJLE=
    on:
      tags: true
      repo: kalabox/kalabox-cli
      condition: $TRAVIS_OS_NAME = linux
  - provider: s3
    access_key_id: AKIAJYMLSO4JBPF57VKA
    secret_access_key:
      secure: q6ewKhbUKHiD825ZraomBp1wAJu4zc/xfrQt0qMJLoiKM/0mSm0qWHBRBcpEVhS+1cDt1DD2ah8Hyvqv5gCsMLSIbDVifQXhQskXOuHj6EzPDlhSGw1od9DlA74zd7ocrwBE/FIRDABaEv5QzTGQesACSsXSPEuCHbL952TYEHGtWr09IPyQlgitzDjwcoyVVCNdKYyNptcTkOx7bbTGqeyptyqrGBj6PYpHEIKmjNa+vFrOJhRR5sm3DfakyYm+UZ+qmDP3bXUREHza/dcriPERdCLodjHJgCz1oI9EU4PC9TBTsZwPEnj3rwKHSdYvlpTgdKdaT0G6PDWXTpNtXOXD0ZNf0FWBaoPARE9oND9EVId1skHdYTnNkXua6CbBzH+H9pJBvNlEnXUjZ29LZOSlJBfvyurM7a2vVxSIjmqEuONTRiWHjVQw/MY3uMouZP0d3KwOQcNu2PrUOzIZhRo7JtPfYcNASvwUKHnmCb4girMqXA/umdTWNCZahGhRB1mcITMtJK9mfv0iFpqHjPKW/rABUJGkNQje4/i81+QGJ1UzGGvmsEvS/drlU5ja6Dve7bwuIKNGVdP1Mzc0E2FtcrhGOT/FMBpxIgp0IFe8RU0CG6fQBsUdLbt7YhIFzimQYx37hgDKqNOv7nxBmFLPSoHjh/9ywVMr2jTJ/6I=
    bucket: cli.kalabox.io
    local-dir: dev_build
    acl: public_read
    region: us-west-1
    skip_cleanup: true
    on:
      repo: kalabox/kalabox-cli
      branch: v0.12
env:
  global:
    - DOCKER_HOST: tcp://10.13.37.100:2375
