#!/bin/bash

# Set up bridge network:
if ! ip link show kbox0 > /dev/null 2>&1
then
  brctl addbr kbox0
fi

# Try a few times
NEXT_WAIT_TIME=0
until ifconfig kbox0 | grep 10.13.37.100 >/dev/null || [ $NEXT_WAIT_TIME -eq 5 ]; do
  ip addr add "10.13.37.100/24" dev kbox0
  ip link set dev kbox0 up
  sleep $(( NEXT_WAIT_TIME++ ))
done
