#!/bin/sh

# We need to use this fauxbin until the resolution of
# https://github.com/syncthing/syncthing/issues/1056
#

if [ -f "/${WEBROOT}/.stfolder" ]; then
  mv /${WEBROOT}/.stfolder /tmp/.stfolder
fi

if [ -f "/${WEBROOT}/.stignore" ]; then
  mv /${WEBROOT}/.stignore /tmp/.stignore
fi

git "$@"

# Move this back
if [ -f "/tmp/.stfolder" ]; then
  mv /tmp/.stfolder /${WEBROOT}/.stfolder
fi

# Move this back
if [ -f "/tmp/.stignore" ]; then
  mv /tmp/.stignore /${WEBROOT}/.stignore
fi
