#!/bin/sh

# We need to use this fauxbin until the resolution of
# https://github.com/syncthing/syncthing/issues/1056
#

if [ -f "/${KBOX_CODEDIR}/.stfolder" ]; then
  mv /${KBOX_CODEDIR}/.stfolder /tmp/.stfolder
fi

if [ -f "/${KBOX_CODEDIR}/.stignore" ]; then
  mv /${KBOX_CODEDIR}/.stignore /tmp/.stignore
fi

git "$@"

# Move this back
if [ -f "/tmp/.stfolder" ]; then
  mv /tmp/.stfolder /${KBOX_CODEDIR}/.stfolder
fi

# Move this back
if [ -f "/tmp/.stignore" ]; then
  mv /tmp/.stignore /${KBOX_CODEDIR}/.stignore
fi
