#!/bin/bash

# @todo: Move all of these into their own postinstall scripts

CONSOLE_USER=$(stat -f '%Su' /dev/console)
CONSOLE_USER_HOME=$(su $CONSOLE_USER -c 'echo $HOME')
VM=Kalabox2

# Fix permissions on binaries
chown -R $CONSOLE_USER:admin /tmp/docker-machine || true
chown -R $CONSOLE_USER:admin /tmp/docker-compose || true
chown -R $CONSOLE_USER:admin /usr/local/bin/kbox || true
chown -R $CONSOLE_USER:staff /Applications/Kalabox.app || true

# Move docker binaries to correct location
mkdir -p $CONSOLE_USER_HOME/.kalabox/bin
mv -f /tmp/docker-compose $CONSOLE_USER_HOME/.kalabox/bin/docker-compose
mv -f /tmp/docker-machine $CONSOLE_USER_HOME/.kalabox/bin/docker-machine

# Place boot2docker ISO in cache & upgrade the boot2docker VM
mkdir -p $CONSOLE_USER_HOME/.docker/machine/cache
cp /usr/local/share/boot2docker/boot2docker.iso $CONSOLE_USER_HOME/.docker/machine/cache/boot2docker.iso

DOCKER_MACHINE="$CONSOLE_USER_HOME/.kalabox/bin/docker-machine"
if [ -d "$CONSOLE_USER_HOME/.docker/machine/machines/$VM" ] && [ -f "$DOCKER_MACHINE" ]; then
  sudo -i -u "$CONSOLE_USER" "$DOCKER_MACHINE" stop "$VM" || true
  cp /usr/local/share/boot2docker/boot2docker.iso "$CONSOLE_USER_HOME/.docker/machine/machines/$VM/boot2docker.iso"
fi

chown -R $CONSOLE_USER:staff $CONSOLE_USER_HOME/.docker
chown -R $CONSOLE_USER:staff $CONSOLE_USER_HOME/.kalabox
