#!/bin/bash

# Declare
declare -r kalabox_bundle_dir=/Applications/Kalabox.app/Contents/MacOS

# Unset some possibly bad things
unset DYLD_LIBRARY_PATH
unset LD_LIBRARY_PATH

# Ensure app perms
chmod -R 755 /Applications/Kalabox.app/

# Symlink the KBOX binary
mkdir -p /usr/local/bin
ln -sF ${kalabox_bundle_dir}/bin/kbox /usr/local/bin/kbox

# Fin
